# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# "bundle exec jekyll serve". If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-theme-architect

title: Zoe's personal website
url: https://emma-sax4.github.io/zoesax301.github.io
markdown: kramdown

github:
  repo_url: https://github.com/zoesax301/zoesax301.github.io
  repo: zoesax301.github.io
  owner_url: https://github.com/zoesax301
  owner: zoesax301

kramdown:
  smart_quotes: ["rdquo", "rsquo", "quot", "quot"]

sass:
  style: compressed

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock

relative_links:
  enabled: true
  collections: true
